apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend-deployment
  labels:
    app: ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
      - name: ai-backend
        image: nikhilshinde143/ai-search-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          value: "AIzaSyATL_N0mpG5ki_AuqjKMssRtxWbDp0exJs"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
spec:
  selector:
    app: ai-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
